# Generated by Django 5.0.6 on 2026-07-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_before', models.IntegerField()),
                ('rating_after', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('PAIC', 'PAIC Result'), ('BAIC', 'BAIC Result'), ('DPP_STREAK', 'DPP Streak'), ('CHAPTER_PERF', 'Chapterwise Performance'), ('TODO_MISS', 'To-Do Missed'), ('TODO_DONE', 'To-Do Completed')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exampaper')),
            ],
        ),
    ]
