name: prepmaster
description: Premium JEE/NEET exam preparation platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1

  # Networking
  dio: ^5.4.3
  retrofit: ^4.1.0

  # Charts (rating graph)
  fl_chart: ^0.68.0

  # Calendar (DPP calendar)
  table_calendar: ^3.1.2

  # Heatmap (activity heatmap)
  flutter_heatmap_calendar: ^1.0.5

  # PDF viewing (question papers)
  syncfusion_flutter_pdfviewer: ^27.2.5

  # Math / LaTeX rendering (question text)
  flutter_math_fork: ^0.7.2

  # Local storage (My Library offline tests)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.3
  image_picker: ^1.1.2

  # Live leaderboard
  web_socket_channel: ^2.4.5

  # Proctoring
  camera: ^0.10.6
  google_mlkit_face_detection: ^0.11.0

  # Secure token storage
  flutter_secure_storage: ^10.3.1


  # Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
