# Generated by Django 5.0.6 on 2026-07-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paper_type', models.CharField(choices=[('DPP', 'Daily Practice Sheet'), ('CHAPTER_TEST', 'Chapterwise Test'), ('PYQ', 'Past Year Question Set'), ('PAIC', 'Premium All India Contest'), ('BAIC', 'Biweekly All India Contest'), ('WEEKLY_PERSONAL', 'Personalized Weekly Test'), ('MOCK_FULL', 'Full Mock Test')], max_length=20)),
                ('exam_style', models.CharField(choices=[('JEE_MAIN', 'JEE Main'), ('JEE_ADV', 'JEE Advanced'), ('NEET', 'NEET')], max_length=10)),
                ('class_level', models.CharField(choices=[('11', '11'), ('12', '12'), ('DROP', 'Dropper')], max_length=4)),
                ('duration_minutes', models.PositiveIntegerField(default=180)),
                ('total_marks', models.PositiveIntegerField(default=300)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('is_live_contest', models.BooleanField(default=False)),
                ('question_paper_pdf', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('solution_pdf', models.FileField(blank=True, null=True, upload_to='solutions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('marks_correct_override', models.FloatField(blank=True, null=True)),
                ('marks_incorrect_override', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
