# Generated by Django 5.0.6 on 2026-07-04 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exampaper'),
        ),
        migrations.AddField(
            model_name='exampaperquestion',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exampaper'),
        ),
        migrations.AddField(
            model_name='exampaperquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='questions',
            field=models.ManyToManyField(through='exams.ExamPaperQuestion', to='content.question'),
        ),
        migrations.AlterUniqueTogether(
            name='exampaperquestion',
            unique_together={('paper', 'order')},
        ),
    ]
