# Generated by Django 5.0.6 on 2026-07-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('submissions_count', models.PositiveIntegerField(default=0)),
                ('dpp_attempted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('numerical_response', models.FloatField(blank=True, null=True)),
                ('omr_bubble', models.CharField(blank=True, max_length=1)),
                ('status', models.CharField(choices=[('NOT_VISITED', 'Not Visited'), ('NOT_ANSWERED', 'Not Answered'), ('ANSWERED', 'Answered'), ('MARKED', 'Marked for Review'), ('ANSWERED_MARKED', 'Answered & Marked')], default='NOT_VISITED', max_length=16)),
                ('is_correct', models.BooleanField(null=True)),
                ('marks_awarded', models.FloatField(default=0)),
                ('is_marked_for_personal_review', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted')], default='IN_PROGRESS', max_length=15)),
                ('is_offline_attempt', models.BooleanField(default=False)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('accuracy_percent', models.FloatField(blank=True, null=True)),
                ('rank_in_paper', models.PositiveIntegerField(blank=True, null=True)),
                ('proctoring_enabled', models.BooleanField(default=False)),
                ('proctoring_flag_count', models.PositiveIntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exampaper')),
            ],
        ),
    ]
