# Generated by Django 5.0.6 on 2026-07-04 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='submissions.attempt'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'paper'], name='submissions_user_id_597d5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['user', 'date'], name='submissions_user_id_133ad1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together={('user', 'date')},
        ),
    ]
