# Generated by Django 5.0.6 on 2026-07-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('class_level', models.CharField(choices=[('11', '11'), ('12', '12'), ('DROP', 'Dropper')], max_length=4)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('estimated_hours', models.FloatField(default=4.0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET')], max_length=4)),
                ('question_type', models.CharField(choices=[('MCQ_SINGLE', 'MCQ Single Correct'), ('MCQ_MULTIPLE', 'MCQ Multiple Correct'), ('NUMERICAL', 'Numerical/Integer'), ('MATCH_COLUMN', 'Match the Column'), ('ASSERTION_REASON', 'Assertion & Reason')], max_length=20)),
                ('marks_correct', models.FloatField(default=4)),
                ('marks_incorrect', models.FloatField(default=-1)),
                ('marks_partial', models.FloatField(default=0)),
                ('instructions_text', models.TextField(blank=True, help_text="Auto-prepended before this category's questions begin in generated PDFs.")),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('exam', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('THEORY', 'Theory'), ('FORMULA', 'Formula Sheet'), ('SOLVED', 'Solved Examples'), ('DPP', 'DPP'), ('PYQ', 'PYQ'), ('REVISION', 'Revision Notes'), ('TEST', 'Chapter Test'), ('ADVANCED', 'Advanced Problems')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('options', models.JSONField(blank=True, default=list)),
                ('numerical_answer', models.FloatField(blank=True, null=True)),
                ('solution_text', models.TextField(blank=True)),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='solutions/')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('exam_shift', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.chapter')),
            ],
        ),
    ]
