# Generated by Django 5.0.6 on 2026-07-04 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('exams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('CONTEST', 'Upcoming Contest'), ('DATE_CHANGE', 'Contest Date Change'), ('RESULT', 'Result / Solution Released'), ('TOPPER', 'Topper Announcement'), ('GENERAL', 'General')], default='GENERAL', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exampaper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
