# Generated by Django 5.0.6 on 2026-07-05 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_announcement'),
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='linked_paper',
            field=models.ForeignKey(blank=True, help_text="The test/DPP/etc. that represents 'completing' this module. Used by the To-Do feature to detect when a linked task is done.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exampaper'),
        ),
    ]
