# Generated by Django 5.0.6 on 2026-07-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('leaderboard', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestleaderboardentry',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submissions.attempt'),
        ),
        migrations.AddField(
            model_name='contestleaderboardentry',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='exams.exampaper'),
        ),
    ]
