# Generated by Django 5.0.6 on 2026-07-04 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboard', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contestleaderboardentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contestleaderboardentry',
            index=models.Index(fields=['paper', 'rank'], name='leaderboard_paper_i_444653_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestleaderboardentry',
            unique_together={('paper', 'user')},
        ),
    ]
