# Generated by Django 5.0.6 on 2026-07-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('NO_FACE', 'No face detected'), ('MULTIPLE_FACES', 'Multiple faces detected'), ('FACE_MISMATCH', 'Face does not match registered profile photo'), ('AUDIO_VOICE', 'Additional voice detected'), ('TAB_SWITCH', 'App switched to background')], max_length=20)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='proctoring_flags/')),
                ('timestamp_in_exam_seconds', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_flags', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
