# Generated by Django 5.0.6 on 2026-07-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proctoring', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsession',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_session', to='submissions.attempt'),
        ),
        migrations.AddField(
            model_name='proctoringflag',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='proctoring.proctoringsession'),
        ),
    ]
