# Generated by Django 5.0.6 on 2026-07-04 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['user', 'due_date'], name='todo_todoit_user_id_ea89a8_idx'),
        ),
    ]
