# Generated by Django 5.0.6 on 2026-07-05 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_module_linked_paper'),
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.module'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
